// ============================================================
// Weekly Digest — Auto-generated portfolio summary
// ============================================================

import { useMemo } from 'react';
import { useStore } from '../lib/store';
import { motion } from 'framer-motion';
import {
    Mail, TrendingUp, AlertTriangle, CheckCircle2,
    Copy, Download
} from 'lucide-react';

export default function WeeklyDigest() {
    const { state, venturesWithStats, portfolioStats } = useStore();

    const today = new Date();
    const weekAgo = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
    const weekLabel = `${weekAgo.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })} — ${today.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`;

    // Recent activity
    const recentTasks = useMemo(() => {
        return state.tasks.filter(t => new Date(t.updated_at) >= weekAgo);
    // eslint-disable-next-line react-hooks/exhaustive-deps -- weekAgo is derived from today which changes every render
    }, [state.tasks]);

    const completedThisWeek = recentTasks.filter(t => t.status === 'done').length;
    const newTasksThisWeek = state.tasks.filter(t => new Date(t.created_at) >= weekAgo).length;
    const blockedNow = state.tasks.filter(t => t.status === 'blocked').length;

    // Venture summaries
    const ventureSummaries = useMemo(() => {
        return venturesWithStats.map(v => {
            const vTasks = state.tasks.filter(t => t.venture_id === v.id);
            const vDone = vTasks.filter(t => t.status === 'done' && new Date(t.updated_at) >= weekAgo).length;
            const vBlocked = vTasks.filter(t => t.status === 'blocked').length;
            const vInProgress = vTasks.filter(t => t.status === 'in-progress').length;
            const upcomingMilestones = state.milestones
                .filter(m => m.venture_id === v.id && new Date(m.target_date) >= today)
                .sort((a, b) => new Date(a.target_date).getTime() - new Date(b.target_date).getTime())
                .slice(0, 1);

            return { ...v, vDone, vBlocked, vInProgress, upcomingMilestones };
        }).filter(v => v.tier !== 'Parked');
    // eslint-disable-next-line react-hooks/exhaustive-deps -- today/weekAgo recalculate each render; data deps are sufficient
    }, [venturesWithStats, state.tasks, state.milestones]);

    // Generate digest text
    const digestText = useMemo(() => {
        let text = `📊 VENTURE COMMAND CENTER — WEEKLY DIGEST\n`;
        text += `${weekLabel}\n\n`;
        text += `═══════════════════════════════════════\n\n`;
        text += `📈 PORTFOLIO OVERVIEW\n`;
        text += `• ${portfolioStats.totalVentures} ventures tracked\n`;
        text += `• ${completedThisWeek} tasks completed this week\n`;
        text += `• ${newTasksThisWeek} new tasks created\n`;
        text += `• ${blockedNow} tasks currently blocked\n`;
        text += `• Avg health score: ${portfolioStats.avgHealth}%\n\n`;

        text += `═══════════════════════════════════════\n\n`;
        text += `🏢 VENTURE UPDATES\n\n`;

        ventureSummaries.forEach(v => {
            const emoji = v.healthScore >= 70 ? '🟢' : v.healthScore >= 40 ? '🟡' : '🔴';
            text += `${emoji} ${v.name} (${v.prefix}) — Health: ${v.healthScore}%\n`;
            text += `   ${v.tier} · ${v.geo} · ${v.stage}\n`;
            text += `   Done: ${v.vDone} | In Prog: ${v.vInProgress} | Blocked: ${v.vBlocked}\n`;
            if (v.upcomingMilestones.length > 0) {
                const ms = v.upcomingMilestones[0];
                text += `   📌 Next milestone: ${ms.name} (${new Date(ms.target_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })})\n`;
            }
            text += `\n`;
        });

        if (blockedNow > 0) {
            text += `═══════════════════════════════════════\n\n`;
            text += `⚠️ BLOCKERS\n\n`;
            state.tasks.filter(t => t.status === 'blocked').forEach(t => {
                const v = state.ventures.find(v => v.id === t.venture_id);
                text += `• [${v?.prefix || '?'}] ${t.title}\n`;
            });
            text += `\n`;
        }

        text += `═══════════════════════════════════════\n`;
        text += `Generated by Venture Command Center\n`;
        return text;
    // eslint-disable-next-line react-hooks/exhaustive-deps -- derived values already capture the necessary state
    }, [ventureSummaries, portfolioStats, completedThisWeek, newTasksThisWeek, blockedNow, weekLabel]);

    const copyToClipboard = () => {
        navigator.clipboard.writeText(digestText);
    };

    const downloadDigest = () => {
        const blob = new Blob([digestText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `weekly-digest-${today.toISOString().split('T')[0]}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div style={{ maxWidth: 800, margin: '0 auto' }}>
            <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginBottom: 'var(--space-5)',
            }}>
                <div>
                    <h2 style={{ fontSize: 'var(--font-size-xl)', fontWeight: 700, color: 'var(--color-text-primary)', marginBottom: 4 }}>
                        <Mail size={20} style={{ display: 'inline', marginRight: 8, verticalAlign: 'middle' }} />
                        Weekly Digest
                    </h2>
                    <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-muted)' }}>{weekLabel}</p>
                </div>
                <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
                    <button className="btn btn-secondary btn-sm" onClick={copyToClipboard}>
                        <Copy size={14} /> Copy
                    </button>
                    <button className="btn btn-primary btn-sm" onClick={downloadDigest}>
                        <Download size={14} /> Download
                    </button>
                </div>
            </div>

            {/* KPI summary */}
            <div className="stat-grid" style={{ marginBottom: 'var(--space-6)' }}>
                {[
                    { label: 'Completed', value: completedThisWeek, icon: CheckCircle2, color: '#10B981' },
                    { label: 'New Tasks', value: newTasksThisWeek, icon: TrendingUp, color: '#3B82F6' },
                    { label: 'Blocked', value: blockedNow, icon: AlertTriangle, color: '#EF4444' },
                    { label: 'Avg Health', value: `${portfolioStats.avgHealth}%`, icon: TrendingUp, color: '#6366F1' },
                ].map((s, i) => (
                    <motion.div key={i} className="stat-card"
                        initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.08 }}>
                        <div className="stat-card-header">
                            <span className="stat-card-label">{s.label}</span>
                            <s.icon size={16} color={s.color} />
                        </div>
                        <div className="stat-card-value" style={{ color: s.color }}>{s.value}</div>
                    </motion.div>
                ))}
            </div>

            {/* Venture cards */}
            <h3 style={{ fontSize: 'var(--font-size-md)', fontWeight: 600, marginBottom: 'var(--space-3)', color: 'var(--color-text-primary)' }}>
                Venture Performance
            </h3>
            <div style={{ display: 'grid', gap: 'var(--space-3)', marginBottom: 'var(--space-6)' }}>
                {ventureSummaries.map((v, i) => (
                    <motion.div key={v.id} className="card card-body" style={{
                        display: 'flex', alignItems: 'center', gap: 'var(--space-4)',
                        borderLeft: `3px solid ${v.color}`,
                    }}
                        initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.06 }}>
                        <div style={{
                            width: 48, height: 48, borderRadius: 'var(--border-radius-md)',
                            background: `${v.color}18`, display: 'flex', alignItems: 'center', justifyContent: 'center',
                            fontWeight: 800, color: v.color, fontSize: 'var(--font-size-lg)', flexShrink: 0,
                        }}>
                            {v.healthScore}
                        </div>
                        <div style={{ flex: 1 }}>
                            <div style={{ fontWeight: 600, color: 'var(--color-text-primary)' }}>{v.name}</div>
                            <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-text-muted)' }}>
                                {v.tier} · {v.stage}
                            </div>
                        </div>
                        <div style={{ display: 'flex', gap: 'var(--space-3)', fontSize: 'var(--font-size-sm)' }}>
                            <div style={{ textAlign: 'center' }}>
                                <div style={{ fontWeight: 600, color: 'var(--color-success)' }}>{v.vDone}</div>
                                <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-text-muted)' }}>Done</div>
                            </div>
                            <div style={{ textAlign: 'center' }}>
                                <div style={{ fontWeight: 600, color: 'var(--color-info)' }}>{v.vInProgress}</div>
                                <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-text-muted)' }}>Active</div>
                            </div>
                            {v.vBlocked > 0 && (
                                <div style={{ textAlign: 'center' }}>
                                    <div style={{ fontWeight: 600, color: 'var(--color-danger)' }}>{v.vBlocked}</div>
                                    <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-text-muted)' }}>Blocked</div>
                                </div>
                            )}
                        </div>
                    </motion.div>
                ))}
            </div>

            {/* Raw text preview */}
            <h3 style={{ fontSize: 'var(--font-size-md)', fontWeight: 600, marginBottom: 'var(--space-3)', color: 'var(--color-text-primary)' }}>
                Plain Text Preview
            </h3>
            <pre className="card card-body" style={{
                fontFamily: 'monospace', fontSize: 'var(--font-size-xs)',
                whiteSpace: 'pre-wrap', color: 'var(--color-text-secondary)',
                maxHeight: 400, overflowY: 'auto', lineHeight: 1.4,
            }}>
                {digestText}
            </pre>
        </div>
    );
}
